package sverigesradio

type EpisodeService service

type AutoGenerated struct {
	ID          int    `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	URL         string `json:"url"`
	Program     struct {
		ID   int    `json:"id"`
		Name string `json:"name"`
	} `json:"program"`
	Audiopreference   string `json:"audiopreference"`
	Audiopriority     string `json:"audiopriority"`
	Audiopresentation string `json:"audiopresentation"`
	Publishdateutc    string `json:"publishdateutc"`
	Imageurl          string `json:"imageurl"`
	Imageurltemplate  string `json:"imageurltemplate"`
	Broadcast         struct {
		Availablestoputc string `json:"availablestoputc"`
		Playlist         struct {
			Duration       int    `json:"duration"`
			Publishdateutc string `json:"publishdateutc"`
			ID             int    `json:"id"`
			URL            string `json:"url"`
			Statkey        string `json:"statkey"`
		} `json:"playlist"`
		Broadcastfiles []struct {
			Duration       int    `json:"duration"`
			Publishdateutc string `json:"publishdateutc"`
			ID             int    `json:"id"`
			URL            string `json:"url"`
			Statkey        string `json:"statkey"`
		} `json:"broadcastfiles"`
	} `json:"broadcast,omitempty"`
	Broadcasttime struct {
		Starttimeutc string `json:"starttimeutc"`
		Endtimeutc   string `json:"endtimeutc"`
	} `json:"broadcasttime,omitempty"`
	Relatedepisodes []interface{} `json:"relatedepisodes"`
	Downloadpodfile struct {
		Title           string `json:"title"`
		Description     string `json:"description"`
		Filesizeinbytes int    `json:"filesizeinbytes"`
		Program         struct {
			ID   int    `json:"id"`
			Name string `json:"name"`
		} `json:"program"`
		Duration       int    `json:"duration"`
		Publishdateutc string `json:"publishdateutc"`
		ID             int    `json:"id"`
		URL            string `json:"url"`
		Statkey        string `json:"statkey"`
	} `json:"downloadpodfile,omitempty"`
	Photographer  string `json:"photographer,omitempty"`
	Listenpodfile struct {
		Title           string `json:"title"`
		Description     string `json:"description"`
		Filesizeinbytes int    `json:"filesizeinbytes"`
		Program         struct {
			ID   int    `json:"id"`
			Name string `json:"name"`
		} `json:"program"`
		Duration       int    `json:"duration"`
		Publishdateutc string `json:"publishdateutc"`
		ID             int    `json:"id"`
		URL            string `json:"url"`
		Statkey        string `json:"statkey"`
	} `json:"listenpodfile,omitempty"`
}
